CityInfo.API/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CityInfo.API.Models;
using CityInfo.API.ViewModels;
using CityInfo.API.Services;
using CityInfo.API.Validation;
using FluentValidation;
using FluentValidation.Results;

namespace CityInfo.API.Controllers
{
    public class AppController: Controller
    {
        private readonly IMailService _mailService;
        public AppController(IMailService mailService)
        {
            _mailService = mailService;
        }
        public IActionResult Index()
        {
            
            return View();
        }
        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Create Crew";
            
            //throw new InvalidOperationException("Bad thing mis coming");
            return View();
        }
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            Valid valid = new Valid();
            ValidationResult results = valid.Validate(model);
            bool validationSucceeded = results.IsValid;
            IList<ValidationFailure> failures = results.Errors;

            if (string.IsNullOrEmpty(model.Member1) && string.IsNullOrEmpty(model.Member2))
            {
                var validationMessage = "Please provide at least one member.";
                ModelState.AddModelError("Member1", validationMessage);
                ModelState.AddModelError("Member2", validationMessage);
            }
            if (model.Member1 == model.Member2)
            {
                var validationMessage = "Members can't be the same person";
                ModelState.AddModelError("Member1", validationMessage);
                ModelState.AddModelError("Member2", validationMessage);
            }
            if (model.Reason == "Other")
            {
                var validationMessage = "Please provide a comment for reason 'Other'";
                ModelState.AddModelError("Comment", validationMessage);
            }

            if (ModelState.IsValid)
            {
                //send email
                _mailService.Send("13bony13@gmail.com.com", model.Reason, $"From: {model.Boss} - {model.Email}, Message: {model.Comment}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }
            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "About US";
            return View();
        }
    }
}

CityInfo.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Hello World: @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-space-shuttle fa-spin fa-stack-1x"></i> Azuri</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
            </div>  <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Index">Home</a></li>
                    <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="App" asp-action="About">About</a></li>
                </ul>
            </div>
            
        </header>
        </div>
   <section class="container">
       <h1 class="text-center">@ViewBag.Title</h1>
       @RenderBody()
       
   </section>
  
   <footer class="container">
        <div class="text-center">Copyrigtht 2017</div>
   </footer>
    


    <script src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)


</body>
</html>